create table questions (
  id varchar(40) primary key,
  area varchar(120) not null,
  topic varchar(160) not null,
  difficulty varchar(30) not null,
  relevance varchar(1) not null,
  competency varchar(80) not null,
  stem varchar(1800) not null,
  options_text varchar(2400) not null,
  correct_index integer not null,
  explanation varchar(1800) not null,
  source_name varchar(300) not null,
  source_url varchar(1000) not null,
  status varchar(30) not null,
  created_at timestamp default current_timestamp not null
);

create table materials (
  id varchar(40) primary key,
  title varchar(500) not null,
  publisher varchar(160) not null,
  item_type varchar(100) not null,
  area varchar(120) not null,
  updated_label varchar(100) not null,
  progress integer not null,
  collection_name varchar(180) not null,
  source_url varchar(1000) not null
);

create table news_items (
  id varchar(40) primary key,
  title varchar(600) not null,
  summary varchar(1600) not null,
  publisher varchar(160) not null,
  published_label varchar(100) not null,
  area varchar(120) not null,
  impact varchar(30) not null,
  source_url varchar(1000) not null,
  related_questions integer not null,
  retrieved_at timestamp default current_timestamp not null
);

create table source_feeds (
  id varchar(40) primary key,
  name varchar(240) not null,
  authority varchar(160) not null,
  feed_type varchar(30) not null,
  status varchar(30) not null,
  last_sync_label varchar(100) not null,
  items_imported integer not null,
  source_url varchar(1000) not null
);

create table readiness_snapshots (
  id integer generated by default as identity primary key,
  label varchar(40) not null,
  score integer not null,
  target integer not null,
  observed_on date not null
);

create index idx_questions_area on questions(area);
create index idx_questions_topic on questions(topic);
create index idx_news_area on news_items(area);
