insert into questions (id, area, topic, difficulty, relevance, competency, stem, options_text, correct_index, explanation, source_name, source_url, status) values
('q-001', 'Medicina', 'Cardiologia', 'Média', 'A', 'Diagnóstico', 'Um homem de 68 anos apresenta dispneia progressiva, ortopneia e edema maleolar. Qual é o exame inicial mais adequado para avaliar a suspeita de insuficiência cardíaca?', 'Ecocardiograma transtorácico|Angio-TC coronária|Prova de esforço|Holter de 24 horas', 0, 'O ecocardiograma avalia estrutura e função cardíacas e é central na confirmação e fenotipagem da insuficiência cardíaca.', 'ESC Guidelines - Heart Failure', 'https://www.escardio.org/Guidelines', 'Revista'),
('q-002', 'Pediatria', 'Infeciologia', 'Fácil', 'A', 'Gestão do doente', 'Uma criança de 3 anos apresenta febre, tosse metálica e estridor inspiratório ligeiro sem sinais de dificuldade respiratória. Qual é a abordagem inicial mais apropriada?', 'Dexametasona oral|Antibiótico endovenoso|Salbutamol nebulizado|Intubação imediata', 0, 'Na laringite aguda ligeira, uma dose de dexametasona reduz sintomas e necessidade de reavaliação.', 'DGS - Normas e orientações', 'https://www.dgs.pt/normas-orientacoes-e-informacoes/normas-e-circulares-normativas.aspx', 'Revista'),
('q-003', 'Cirurgia', 'Abdómen agudo', 'Difícil', 'A', 'Diagnóstico', 'Uma mulher de 74 anos com fibrilhação auricular apresenta dor abdominal súbita intensa, desproporcionada ao exame objetivo. Qual é o diagnóstico mais provável?', 'Isquemia mesentérica aguda|Colecistite aguda|Diverticulite|Pancreatite aguda', 0, 'A dor intensa desproporcionada aos achados, sobretudo com risco embólico, é clássica de isquemia mesentérica aguda.', 'European Society for Vascular Surgery', 'https://esvs.org/guidelines/', 'Revista'),
('q-004', 'Ginecologia/Obstetrícia', 'Hipertensão na gravidez', 'Média', 'A', 'Gestão do doente', 'Uma grávida de 34 semanas apresenta pressão arterial de 168/112 mmHg e cefaleias persistentes. Qual é a prioridade imediata?', 'Tratar a hipertensão grave e prevenir convulsões|Aguardar proteinúria de 24 horas|Induzir o parto sem estabilização|Reavaliar em consulta dentro de uma semana', 0, 'Hipertensão grave com sintomas neurológicos requer estabilização materna urgente e profilaxia de eclâmpsia.', 'DGS - Saúde materna', 'https://www.dgs.pt/', 'Revista'),
('q-005', 'Psiquiatria', 'Perturbações do humor', 'Média', 'B', 'Diagnóstico', 'Uma pessoa com episódio depressivo refere ideias de morte, plano definido e acesso ao meio. Qual é a resposta mais adequada?', 'Avaliação urgente de risco e garantia de segurança|Iniciar psicoterapia e rever em um mês|Recomendar exercício e higiene do sono|Pedir apenas análises gerais', 0, 'Plano, intenção e acesso ao meio indicam risco elevado, exigindo avaliação urgente e medidas imediatas de segurança.', 'DGS - Saúde mental', 'https://www.dgs.pt/', 'Revista'),
('q-006', 'Medicina', 'Endocrinologia', 'Difícil', 'B', 'Mecanismos da doença', 'Numa pessoa com hiponatremia hipotónica, euvolemia clínica, osmolaridade urinária elevada e função tiroideia normal, qual é a hipótese mais provável?', 'Síndrome de secreção inapropriada de ADH|Diabetes insípida|Hiperaldosteronismo primário|Polidipsia primária', 0, 'A combinação de hiponatremia hipotónica, euvolemia e urina inapropriadamente concentrada é compatível com SIADH após excluir outras causas.', 'European Society of Endocrinology', 'https://www.ese-hormones.org/', 'Revista'),
('q-007', 'Medicina', 'Pneumologia', 'Média', 'A', 'Gestão do doente', 'Uma pessoa com exacerbação de DPOC apresenta acidose respiratória e trabalho respiratório aumentado apesar do tratamento inicial. Qual é o suporte ventilatório preferencial se não houver contraindicações?', 'Ventilação não invasiva|Oxigénio de alto débito isolado|Intubação imediata em todos os casos|Nenhum suporte ventilatório', 0, 'A ventilação não invasiva reduz trabalho respiratório e necessidade de intubação na exacerbação hipercápnica apropriada.', 'GOLD Report', 'https://goldcopd.org/', 'Revista'),
('q-008', 'Pediatria', 'Neonatologia', 'Difícil', 'A', 'Prevenção', 'Qual é a medida mais eficaz para reduzir transmissão vertical de infeção conhecida durante o seguimento pré-natal?', 'Identificação precoce e intervenção específica segundo o agente|Antibiótico universal no terceiro trimestre|Cesariana eletiva em todas as situações|Suspensão universal da amamentação', 0, 'A estratégia depende do agente e começa pelo rastreio e intervenção dirigida, evitando medidas universais sem indicação.', 'DGS - Saúde reprodutiva', 'https://www.dgs.pt/', 'Revista'),
('q-009', 'Cirurgia', 'Trauma', 'Média', 'A', 'Gestão do doente', 'Num traumatizado instável com suspeita de hemorragia intra-abdominal, qual é o exame rápido realizado à cabeceira?', 'Ecografia FAST|Ressonância magnética|Colonoscopia|Cintigrafia', 0, 'A ecografia FAST permite pesquisar rapidamente líquido livre no doente traumatizado instável.', 'European trauma guidance', 'https://www.erc.edu/', 'Revista'),
('q-010', 'Psiquiatria', 'Ansiedade', 'Fácil', 'B', 'Diagnóstico', 'Episódios recorrentes de medo intenso com sintomas autonómicos, início súbito e preocupação persistente com novos episódios sugerem que diagnóstico?', 'Perturbação de pânico|Perturbação obsessivo-compulsiva|Distimia|Delirium', 0, 'Ataques inesperados recorrentes seguidos de preocupação ou alteração comportamental sustentam perturbação de pânico.', 'DGS - Saúde mental', 'https://www.dgs.pt/', 'Revista');

insert into materials (id, title, publisher, item_type, area, updated_label, progress, collection_name, source_url) values
('m-001', 'Matriz de conhecimentos e competências PNA', 'Diário da República', 'Matriz oficial', 'Transversal', '20 mar 2024', 82, 'Base oficial PNA', 'https://diariodarepublica.pt/dr/detalhe/despacho/3029-2024-856476499'),
('m-002', 'Normas e circulares normativas', 'Direção-Geral da Saúde', 'Coleção de normas', 'Medicina', 'Sincronizado hoje', 46, 'Normas clínicas', 'https://www.dgs.pt/normas-orientacoes-e-informacoes/normas-e-circulares-normativas.aspx'),
('m-003', 'Regulamento da PNA 2025', 'ACSS / GPNA', 'Regulamento', 'Transversal', '11 nov 2025', 100, 'Base oficial PNA', 'https://www.acss.min-saude.pt/category/profissionais/carreiras/medica/internato-medico/prova-nacional-de-acesso/'),
('m-004', 'Segurança de medicamentos - atualizações', 'INFARMED', 'Feed temático', 'Farmacologia', 'Sincronizado há 2 h', 21, 'Atualizações terapêuticas', 'https://www.infarmed.pt/web/infarmed/rss');

insert into news_items (id, title, summary, publisher, published_label, area, impact, source_url, related_questions) values
('n-001', 'Aviso de abertura do procedimento para o Internato Médico 2027', 'A PNA 2026 está indicada para 25 de novembro. O regulamento anual deve ser confirmado quando publicado.', 'Diário da República', '31 ago 2026', 'PNA', 'Alto', 'https://diariodarepublica.pt/dr/detalhe/aviso/20582-2026-1159742867', 0),
('n-002', 'Atualizações recentes de normas clínicas nacionais', 'Foram detetadas publicações com ligação a tópicos da matriz. Revê o texto original antes de atualizar apontamentos.', 'DGS', '28 ago 2026', 'Medicina', 'Médio', 'https://www.dgs.pt/normas-orientacoes-e-informacoes/normas-e-circulares-normativas.aspx', 14),
('n-003', 'Novas comunicações de segurança do medicamento', 'O feed INFARMED inclui novos itens potencialmente relevantes para farmacologia e gestão terapêutica.', 'INFARMED', '26 ago 2026', 'Farmacologia', 'Médio', 'https://www.infarmed.pt/web/infarmed/rss', 8);

insert into source_feeds (id, name, authority, feed_type, status, last_sync_label, items_imported, source_url) values
('s-001', 'PNA e Internato Médico', 'ACSS', 'Web', 'Ativa', 'Há 18 min', 18, 'https://www.acss.min-saude.pt/category/profissionais/carreiras/medica/internato-medico/prova-nacional-de-acesso/'),
('s-002', 'Diário da República', 'INCM', 'RSS', 'Ativa', 'Há 34 min', 126, 'https://diariodarepublica.pt/dr/geral/notificacoes/rss'),
('s-003', 'Normas e orientações', 'DGS', 'RSS', 'Ativa', 'Há 1 h', 84, 'https://www.dgs.pt/paginas-de-sistema/rss.aspx'),
('s-004', 'Segurança do medicamento', 'INFARMED', 'RSS', 'Ativa', 'Há 2 h', 47, 'https://www.infarmed.pt/web/infarmed/rss'),
('s-005', 'Literatura biomédica', 'Europe PMC', 'API', 'Ativa', 'Há 4 h', 312, 'https://europepmc.org/developers');

insert into readiness_snapshots (label, score, target, observed_on) values
('Mai', 51, 58, '2026-05-01'),
('Jun', 57, 63, '2026-06-01'),
('Jul', 61, 68, '2026-07-01'),
('1 Ago', 64, 72, '2026-08-01'),
('15 Ago', 68, 76, '2026-08-15'),
('Hoje', 72, 79, '2026-09-02'),
('Previsão', 81, 84, '2026-11-25');
