import type { AceData } from '@/lib/types';

export const demoData: AceData = {
  origin: 'demo',
  dashboard: {
    learnerName: 'Marta',
    targetLabel: 'PNA 2026 → IM 2027',
    examDate: '25 de novembro de 2026',
    daysToExam: 84,
    readiness: 72,
    readinessDelta: 4,
    readinessConfidence: 'Alta',
    answeredQuestions: 1286,
    studyMinutesThisWeek: 222,
    weeklyGoalMinutes: 300,
    currentStreakDays: 8,
    recommendation: {
      title: 'Consolidar insuficiência cardíaca',
      description:
        'O desempenho neste tema está 14 pontos abaixo da média de Medicina Interna. Uma sessão focada pode fechar esta lacuna.',
      questionCount: 12,
      estimatedMinutes: 18,
    },
    subjectScores: [
      { name: 'Medicina', score: 82, coverage: 88, trend: 5, status: 'Forte' },
      { name: 'Pediatria', score: 76, coverage: 73, trend: 3, status: 'Forte' },
      { name: 'Cirurgia', score: 69, coverage: 67, trend: 2, status: 'A consolidar' },
      { name: 'Psiquiatria', score: 66, coverage: 61, trend: -1, status: 'A consolidar' },
      { name: 'Ginecologia/Obstetrícia', score: 58, coverage: 49, trend: 1, status: 'Prioridade' },
    ],
    weeklyActivity: [
      { label: 'Seg', questions: 28, minutes: 47 },
      { label: 'Ter', questions: 34, minutes: 55 },
      { label: 'Qua', questions: 18, minutes: 31 },
      { label: 'Qui', questions: 42, minutes: 62 },
      { label: 'Sex', questions: 12, minutes: 22 },
      { label: 'Sáb', questions: 0, minutes: 0 },
      { label: 'Dom', questions: 5, minutes: 5 },
    ],
  },
  readinessHistory: [
    { label: 'Mai', score: 51, target: 58 },
    { label: 'Jun', score: 57, target: 63 },
    { label: 'Jul', score: 61, target: 68 },
    { label: '1 Ago', score: 64, target: 72 },
    { label: '15 Ago', score: 68, target: 76 },
    { label: 'Hoje', score: 72, target: 79 },
    { label: 'Previsão', score: 81, target: 84 },
  ],
  questions: [
    {
      id: 'q-001',
      area: 'Medicina',
      topic: 'Cardiologia',
      difficulty: 'Média',
      relevance: 'A',
      competency: 'Diagnóstico',
      stem: 'Um homem de 68 anos apresenta dispneia progressiva, ortopneia e edema maleolar. Qual é o exame inicial mais adequado para avaliar a suspeita de insuficiência cardíaca?',
      options: ['Ecocardiograma transtorácico', 'Angio-TC coronária', 'Prova de esforço', 'Holter de 24 horas'],
      correctIndex: 0,
      explanation: 'O ecocardiograma avalia a estrutura e função cardíacas e é central na confirmação e fenotipagem da insuficiência cardíaca.',
      source: 'ESC Guidelines — Heart Failure',
      sourceUrl: 'https://www.escardio.org/Guidelines',
      status: 'Revista',
    },
    {
      id: 'q-002',
      area: 'Pediatria',
      topic: 'Infeciologia',
      difficulty: 'Fácil',
      relevance: 'A',
      competency: 'Gestão do doente',
      stem: 'Uma criança de 3 anos apresenta febre, tosse metálica e estridor inspiratório ligeiro sem sinais de dificuldade respiratória. Qual é a abordagem inicial mais apropriada?',
      options: ['Dexametasona oral', 'Antibiótico endovenoso', 'Salbutamol nebulizado', 'Intubação imediata'],
      correctIndex: 0,
      explanation: 'Na laringite aguda ligeira, uma dose de dexametasona reduz sintomas e necessidade de reavaliação.',
      source: 'DGS — Normas e orientações',
      sourceUrl: 'https://www.dgs.pt/normas-orientacoes-e-informacoes/normas-e-circulares-normativas.aspx',
      status: 'Revista',
    },
    {
      id: 'q-003',
      area: 'Cirurgia',
      topic: 'Abdómen agudo',
      difficulty: 'Difícil',
      relevance: 'A',
      competency: 'Diagnóstico',
      stem: 'Uma mulher de 74 anos com fibrilhação auricular apresenta dor abdominal súbita intensa, desproporcionada ao exame objetivo. Qual é o diagnóstico mais provável?',
      options: ['Isquemia mesentérica aguda', 'Colecistite aguda', 'Diverticulite', 'Pancreatite aguda'],
      correctIndex: 0,
      explanation: 'A dor intensa desproporcionada aos achados, sobretudo com risco embólico, é clássica de isquemia mesentérica aguda.',
      source: 'European Society for Vascular Surgery guideline',
      sourceUrl: 'https://esvs.org/guidelines/',
      status: 'Revista',
    },
    {
      id: 'q-004',
      area: 'Ginecologia/Obstetrícia',
      topic: 'Hipertensão na gravidez',
      difficulty: 'Média',
      relevance: 'A',
      competency: 'Gestão do doente',
      stem: 'Uma grávida de 34 semanas apresenta pressão arterial de 168/112 mmHg e cefaleias persistentes. Qual é a prioridade imediata?',
      options: ['Tratar a hipertensão grave e prevenir convulsões', 'Aguardar proteinúria de 24 horas', 'Induzir o parto sem estabilização', 'Reavaliar em consulta dentro de uma semana'],
      correctIndex: 0,
      explanation: 'Hipertensão grave com sintomas neurológicos requer estabilização materna urgente e profilaxia de eclâmpsia.',
      source: 'DGS — Saúde materna',
      sourceUrl: 'https://www.dgs.pt/',
      status: 'Revista',
    },
    {
      id: 'q-005',
      area: 'Psiquiatria',
      topic: 'Perturbações do humor',
      difficulty: 'Média',
      relevance: 'B',
      competency: 'Diagnóstico',
      stem: 'Uma pessoa com episódio depressivo refere ideias de morte, plano definido e acesso ao meio. Qual é a resposta mais adequada?',
      options: ['Avaliação urgente de risco e garantia de segurança', 'Iniciar psicoterapia e rever em um mês', 'Recomendar exercício e higiene do sono', 'Pedir apenas análises gerais'],
      correctIndex: 0,
      explanation: 'Plano, intenção e acesso ao meio indicam risco elevado, exigindo avaliação urgente e medidas imediatas de segurança.',
      source: 'DGS — Saúde mental',
      sourceUrl: 'https://www.dgs.pt/',
      status: 'Revista',
    },
    {
      id: 'q-006',
      area: 'Medicina',
      topic: 'Endocrinologia',
      difficulty: 'Difícil',
      relevance: 'B',
      competency: 'Mecanismos da doença',
      stem: 'Numa pessoa com hiponatremia hipotónica, euvolemia clínica, osmolaridade urinária elevada e função tiroideia normal, qual é a hipótese mais provável?',
      options: ['Síndrome de secreção inapropriada de ADH', 'Diabetes insípida', 'Hiperaldosteronismo primário', 'Polidipsia primária'],
      correctIndex: 0,
      explanation: 'A combinação de hiponatremia hipotónica, euvolemia e urina inapropriadamente concentrada é compatível com SIADH após excluir outras causas.',
      source: 'European hyponatraemia guideline',
      sourceUrl: 'https://www.ese-hormones.org/',
      status: 'Revista',
    },
  ],
  materials: [
    {
      id: 'm-001',
      title: 'Matriz de conhecimentos e competências PNA',
      publisher: 'Diário da República',
      type: 'Matriz oficial',
      area: 'Transversal',
      updatedAt: '20 mar 2024',
      progress: 82,
      collection: 'Base oficial PNA',
      sourceUrl: 'https://diariodarepublica.pt/dr/detalhe/despacho/3029-2024-856476499',
    },
    {
      id: 'm-002',
      title: 'Normas e circulares normativas',
      publisher: 'Direção-Geral da Saúde',
      type: 'Coleção de normas',
      area: 'Medicina',
      updatedAt: 'Sincronizado hoje',
      progress: 46,
      collection: 'Normas clínicas',
      sourceUrl: 'https://www.dgs.pt/normas-orientacoes-e-informacoes/normas-e-circulares-normativas.aspx',
    },
    {
      id: 'm-003',
      title: 'Regulamento da PNA 2025',
      publisher: 'ACSS / GPNA',
      type: 'Regulamento',
      area: 'Transversal',
      updatedAt: '11 nov 2025',
      progress: 100,
      collection: 'Base oficial PNA',
      sourceUrl: 'https://www.acss.min-saude.pt/category/profissionais/carreiras/medica/internato-medico/prova-nacional-de-acesso/',
    },
    {
      id: 'm-004',
      title: 'Segurança de medicamentos — atualizações',
      publisher: 'INFARMED',
      type: 'Feed temático',
      area: 'Farmacologia',
      updatedAt: 'Sincronizado há 2 h',
      progress: 21,
      collection: 'Atualizações terapêuticas',
      sourceUrl: 'https://www.infarmed.pt/web/infarmed/rss',
    },
  ],
  news: [
    {
      id: 'n-001',
      title: 'Aviso de abertura do procedimento para o Internato Médico 2027',
      summary: 'A PNA 2026 está indicada para 25 de novembro. O regulamento anual deve ser confirmado quando publicado.',
      publisher: 'Diário da República',
      publishedAt: '31 ago 2026',
      area: 'PNA',
      impact: 'Alto',
      sourceUrl: 'https://diariodarepublica.pt/dr/detalhe/aviso/20582-2026-1159742867',
      relatedQuestions: 0,
    },
    {
      id: 'n-002',
      title: 'Atualizações recentes de normas clínicas nacionais',
      summary: 'Foram detetadas publicações com ligação a tópicos da matriz. Revê o texto original antes de atualizar apontamentos.',
      publisher: 'DGS',
      publishedAt: '28 ago 2026',
      area: 'Medicina',
      impact: 'Médio',
      sourceUrl: 'https://www.dgs.pt/normas-orientacoes-e-informacoes/normas-e-circulares-normativas.aspx',
      relatedQuestions: 14,
    },
    {
      id: 'n-003',
      title: 'Novas comunicações de segurança do medicamento',
      summary: 'O feed INFARMED inclui novos itens potencialmente relevantes para farmacologia e gestão terapêutica.',
      publisher: 'INFARMED',
      publishedAt: '26 ago 2026',
      area: 'Farmacologia',
      impact: 'Médio',
      sourceUrl: 'https://www.infarmed.pt/web/infarmed/rss',
      relatedQuestions: 8,
    },
  ],
  sources: [
    { id: 's-001', name: 'PNA e Internato Médico', authority: 'ACSS', type: 'Web', status: 'Ativa', lastSync: 'Há 18 min', itemsImported: 18, url: 'https://www.acss.min-saude.pt/category/profissionais/carreiras/medica/internato-medico/prova-nacional-de-acesso/' },
    { id: 's-002', name: 'Diário da República', authority: 'INCM', type: 'RSS', status: 'Ativa', lastSync: 'Há 34 min', itemsImported: 126, url: 'https://diariodarepublica.pt/dr/geral/notificacoes/rss' },
    { id: 's-003', name: 'Normas e orientações', authority: 'DGS', type: 'RSS', status: 'Ativa', lastSync: 'Há 1 h', itemsImported: 84, url: 'https://www.dgs.pt/paginas-de-sistema/rss.aspx' },
    { id: 's-004', name: 'Segurança do medicamento', authority: 'INFARMED', type: 'RSS', status: 'Ativa', lastSync: 'Há 2 h', itemsImported: 47, url: 'https://www.infarmed.pt/web/infarmed/rss' },
    { id: 's-005', name: 'Literatura biomédica', authority: 'Europe PMC', type: 'API', status: 'Ativa', lastSync: 'Há 4 h', itemsImported: 312, url: 'https://europepmc.org/developers' },
  ],
};
